version: '3.11'

services:
  multilingual-rag:
    build: .
    container_name: multilingual-rag-app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      # Optionally pass environment variables from a file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEFAULT_MODEL_NAME=${DEFAULT_MODEL_NAME}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - DEFAULT_EMBEDDING_MODEL=${DEFAULT_EMBEDDING_MODEL}
      - DEFAULT_BREAKPOINT_THRESHOLD=${DEFAULT_BREAKPOINT_THRESHOLD}
      - DEFAULT_BUFFER_SIZE=${DEFAULT_BUFFER_SIZE}
      - DEFAULT_TOP_K=${DEFAULT_TOP_K}
    volumes:
      - .:/app
    restart: unless-stopped
    # Uncomment below if you want to use a .env file for environment variables
    env_file:
      - .env
